[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "smartclass"
version = "0.0.1"
description = "Short Description TODO"
authors = [
    {name = "Adriano Rutz", email = "rutz@imsb.biol.ethz.ch"},
]
requires-python = ">=3.13.0,<4.0.0"
keywords = [
    "cheminformatics",
    "openData",
    "classification",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Framework :: Pytest",
    "Framework :: tox",
    "Framework :: Sphinx",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]
license = {text = "LICENSE"}
readme = "README.rst"

dependencies = [
    "chembl-downloader>=0.5.2,<1.0.0",
    "click>=8.3.0,<9.0.0",
    "importlib-resources>=6.5.2,<7.0.0",
    "myopic-mces>=1.0.1,<2.0.0",
    "polars>=1.34.0,<2.0.0",
    "pooch>=1.8.2,<2.0.0",
    "pystow>=0.7.8,<1.0.0",
    "rdcanon>=0.1.2,<1.0.0",
    "rdkit>=2025.9.1,<2026.0.0",
    "requests>=2.32.3,<3.0.0",
    "tqdm>=4.67.1,<5.0.0",
]

[dependency-groups]
dev = [
    "coverage>=7.10.7,<8.0.0",
    "pre-commit>=4.3.0,<5.0.0",
    "pytest>=8.4.2,<9.0.0",
    "pytest-asyncio>=1.2.0,<2.0.0",
    "pytest-cov>=7.0.0,<8.0.0",
    "pytest-mock>=3.15.1,<4.0.0",
    "pytest-xdist>=3.8.0,<4.0.0",
    "requests-mock>=1.12.1,<2.0.0",
]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[options.entry_points]
console_scripts = "smartclass = smartclass.cli:main"

[options.package_data]
smartclass = "data/.*"

[project.scripts]
smartclass = "smartclass.cli:main"

[project.urls]
homepage = "https://gitlab.ethz.ch/zambonilab/smartclass"
repository = "https://gitlab.ethz.ch/zambonilab/smartclass"
documentation = "https://smartclass.readthedocs.io"

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["smartclass"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
fix = true

[tool.ruff.format]
preview = true

[tool.setuptools]
py-modules = ["smartclass"]

[tool.ty.rules]
unresolved-import = "ignore"
