[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "smartclass"
version = "0.0.1"
description = "Short Description TODO"
authors = [
    {name = "Adriano Rutz", email = "rutz@imsb.biol.ethz.ch"},
]
requires-python = "<3.14.0,>=3.13.0"
keywords = [
    "cheminformatics",
    "openData",
    "classification",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Framework :: Pytest",
    "Framework :: tox",
    "Framework :: Sphinx",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]
license = {text = "LICENSE"}
readme = "README.rst"

dependencies = [
    "chembl-downloader<1.0.0,>=0.5.1",
    "click<9.0.0,>=8.1.7",
    "importlib-resources<7.0.0,>=6.5.2",
    "myopic-mces<2.0.0,>=1.0.1",
    "polars<2.0.0,>=1.29.0",
    "pooch<2.0.0,>=1.8.2",
    "pystow<1.0.0,>=0.5.3",
    "rdcanon<1.0.0,>=0.1.2",
    "rdkit<2026.0.0,>=2025.3.1",
    "requests<3.0.0,>=2.32.3",
    "tqdm<5.0.0,>=4.67.1",
]

[dependency-groups]
dev = [
    "black<25.0.0,>=24.10.0",
    "coverage<8.0.0,>=7.8.0",
    "deptry<1.0.0,>=0.23.0",
    "flake8<8.0.0,>=7.2.0",
    "importlib-metadata<9.0.0,>=8.7.0",
    "isort<7.0.0,>=6.0.1",
    "mypy<2.0.0,>=1.17.1",
    "pre-commit<5.0.0,>=4.2.0",
    "pytest<9.0.0,>=8.3.5",
    "pytest-asyncio<1.0.0,>=0.26.0",
    "pytest-cov<7.0.0,>=6.1.1",
    "pytest-mock<4.0.0,>=3.14.0",
    "pytest-xdist<4.0.0,>=3.6.1",
    "requests-mock<2.0.0,>=1.12.1",
    "tox<5.0.0,>=4.25.0",
]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[options.entry_points]
console_scripts = "smartclass = smartclass.cli:main"

[options.package_data]
smartclass = "data/.*"

[project.scripts]
smartclass = "smartclass.cli:main"

[project.urls]
homepage = "https://gitlab.ethz.ch/zambonilab/smartclass"
repository = "https://gitlab.ethz.ch/zambonilab/smartclass"
documentation = "https://smartclass.readthedocs.io"

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["smartclass"]

[tool.mypy]
files = ["smartclass"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
fix = true

[tool.ruff.format]
preview = true

[tool.setuptools]
py-modules = ["smartclass"]
