name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libfreetype6-dev libjpeg-turbo8-dev liblapack-dev libopenblas-dev libpng-dev libtiff-dev
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Run tests for PR
        env:
          PYTHONDONTWRITEBYTECODE: 1
        run: |
          uv run pytest --cov-config=.coveragerc --cov=.
          uv run coverage xml
      - uses: orgoro/coverage@v3.1
        if: github.event_name == 'pull_request'
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.98
      - name: Ensure pip is installed
        run: |
          uv run pip install --upgrade pip
      - name: Run tests
        if: github.event_name != 'pull_request'
        run: |
          uv run coverage report
      - name: Build and deploy documentation
        run: |
          uv sync --group docs
          uv run sphinx-build -b html docs/source docs/_build/html
          uv run ghp-import -n -p -f docs/_build/html
        if: github.event_name == 'push'
