name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libfreetype6-dev libjpeg-turbo8-dev liblapack-dev libopenblas-dev libpng-dev libtiff-dev pkg-config
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Run tests for PR
        env:
          PYTHONDONTWRITEBYTECODE: 1
        run: |
          uv run pytest --cov-config=.coveragerc --cov=.
          uv run coverage xml
      - uses: orgoro/coverage@v3.1
        if: github.event_name == 'pull_request'
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.98
      - name: Run tests
        if: github.event_name != 'pull_request'
        run: |
          uv run coverage report
      - name: Build documentation
        run: |
          uv run python3 -m pip install -r docs/requirements.in
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/source
          uv run sphinx-build -b html . _build
          cp -r _build/* ../../gh-pages/
      - uses: JamesIves/github-pages-deploy-action@v4.6.0
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: gh-pages
